### ISSUE TITLE
User Story: Deployment & Documentation

### ISSUE THREAD

**Issue by SoroushGReza** [SoroushGReza/my-plans#12]
As a **developer**, I want to **deploy the application for public access** and make sure that **everything is documented**.

**Tasks**:
- [ ] Prepare the application for deployment to Heroku.
- [ ] Document the deployment process in README file.
- [ ] Make sure everything is documented in the README file.
