### ISSUE TITLE
User Story: Share Tasks

### ISSUE THREAD

**Issue by SoroushGReza** [SoroushGReza/my-plans#9]
As a **User**, I want to be able to **share my tasks or shown them as "public" if I choose to**.

**Tasks**:

- [ ] Create a shared task view.
- [ ] Create functionality så share task with others through email.
- [ ] Implement functionality to add and remove collaborators from tasks.
